In [1]:
import numpy as np

In [5]:
matriz = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print(matriz.ndim)
print(matriz.shape)

2
(3, 3)


In [6]:
# Buscar elemento na linha 1 e coluna 2

elemento = matriz[1, 2]
elemento

np.int64(60)

Obs: Em um matriz a indexação começa com 0 tanto nas linhas como colunas

In [7]:
# Pegar dados da primeira linha

linha_0 = matriz[0]
linha_0

array([10, 20, 30])

In [8]:
# Acessando a coluna 1

coluna_1 = matriz[:, 1]
coluna_1

array([20, 50, 80])

In [10]:
# Fatiamento para obter um subArray

sub_array = matriz[0:2, 1:3]
sub_array

array([[20, 30],
       [50, 60]])

In [14]:
# Usando mascara para acessar elementos atraves de condições

mascara = matriz > 50
mascara

elementos_maiores_que_50 = matriz[mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [16]:
# Modificando elementos na Matriz

matriz[1, 2] = 100
matriz

array([[ 10,  20,  30],
       [ 40, 100, 100],
       [ 70,  80,  90]])