## Entendendo Dimensões com Numpy

In [1]:
import numpy as np

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim) # Número de dimensões
print(array_1d.shape) # Formato array
array_1d    

# Lista de Dados, como séries temporais ou coleções de valores

1
(5,)


array([1, 2, 3, 4, 5])

In [4]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim) # Número de dimensões
print(array_2d.shape) # Formato do array
array_2d

# Matrizes, tabelas de dados, imagens em escala de cinza


2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
print(array_3d.ndim) # Número de dimensões
print(array_3d.shape) # Formato do array
array_3d

# Imagens em cores (cada matriz representando um canal de cor, como RGB)

3
(1, 4, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])