## Fatiando Array

In [1]:
import numpy as np

In [2]:
matriz = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]])

In [3]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
# Fatiando as duas primeiras linhas

fatiando_linhas = matriz[0:2, :]
fatiando_linhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# Fatiando as três primeiras colunas

fatiando_colunas = matriz[: , 0:3]
fatiando_colunas

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])