## Funções Universais

In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
matriz = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]])
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### 1 - Função Adição Numpy (add)

- A função 'add' funciona como adição, pois adiciona valor aos elementos do array tanto 1D, 2D e 3D

In [4]:
sumArray1D = np.add(array, 10)
sumArray2D = np.add(matriz, 10)

In [5]:
print(sumArray1D)
print(sumArray2D)

[11 12 13 14 15]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### 2 - Função de Subtração Numpy (subtract)

- A função 'subtract' funciona como subtração, pois retira valor aos elementos do array tanto 1D, 2D e 3D

In [6]:
subtracaoArray1D = np.subtract(sumArray1D, 5)
subtracaoArray2D = np.subtract(sumArray2D, 5)

In [7]:
print(subtracaoArray1D)
print(subtracaoArray2D)

[ 6  7  8  9 10]
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### 3 - Função de Divisão Numpy (divide)

- A função 'divide' funciona como divisão, pois divide valor dos elementos do array tanto 1D, 2D e 3D

In [8]:
divisaoArray1D = np.divide(array, 2)
divisaoArray2D = np.divide(matriz, 2)

In [9]:
print(divisaoArray1D)
print(divisaoArray2D)

[0.5 1.  1.5 2.  2.5]
[[ 0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5. ]
 [ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]]


### 4 - Função de Multiplicação Numpy (multiply)

- A função 'multiply' funciona como multiplicação, pois multiplica os valores de cada elemento do array tanto 1D, 2D e 3D

In [10]:
multilplicacaoArray1D = np.multiply(array, 10)
multilplicacaoArray2D = np.multiply(matriz, 5)

In [11]:
print(multilplicacaoArray1D)
print(multilplicacaoArray2D)

[10 20 30 40 50]
[[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]]


### 5 - Funções Trigonométricas com Numpy

In [12]:
seno = np.sin(array)
seno

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [13]:
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

### 6 - Funções Estatísticas

In [14]:
media = np.mean(array)
media

np.float64(3.0)

In [15]:
mediana = np.median(array)
mediana

np.float64(3.0)

In [16]:
maximo = np.max(array)
maximo

np.int64(5)

In [17]:
desvioPadrao = np.std(array)
desvioPadrao

np.float64(1.4142135623730951)

### 7 - Funções de comparações

In [18]:
comparacaoMaoirQue3 = array > 3
comparacaoMaoirQue3

array([False, False, False,  True,  True])

### 8 - Combinado funções

In [19]:
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

### 9 - Funções Exponenciais

In [20]:
exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

### 10 - Funções de Logaritmo

In [21]:
logaritmo = np.log(array)
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### 11 - Funções de Arredondamento

In [22]:
arrendodado = np.round(array / 2)
arrendodado

array([0., 1., 2., 2., 2.])