### Copy e View

- Uma nova cópia do array é criada em memória. Isso significa que as 2 matrizes (original e a cópia) são independentes uma da outra.

### View 

- Não é criada em uma nova cópia na memória.
- A view compratilha os mesmos dados que o array original.

In [2]:
import numpy as np

In [3]:
array_original = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8]])
array_original

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1 - Cópia Rasa (View)


In [ ]:
array_view = array_original[1:, 1:]

array_view

array([[6, 7, 8]])

In [5]:
array_view[0, 0] = 99
array_view

array([[99,  7,  8]])

In [6]:
array_original

array([[ 1,  2,  3,  4],
       [ 5, 99,  7,  8]])

### 2 - Cópia Profunda (Copy)

In [ ]:
array_copia = array_original.copy()
array_copia[1, 1] = 6

print(array_copia)
print(array_original)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 5 99  7  8]]
